name: CI Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
      - dev


jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile project
        run: mvn compile -Djava.awt.headless=true 

      - name: Install dependencies
        run: mvn install --batch-mode --update-snapshots -Djava.awt.headless=true

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run tests
        run: mvn test -Djava.awt.headless=true

  format-check:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Java formatting with custom rules
        run: |
          mvn com.github.spotbugs:spotbugs-maven-plugin:check -DconfigFile=../config/checkStyle.xml || (
            echo "Code formatting does not match the custom style rules. Run the following command locally to fix it:"
            echo "mvn com.github.spotbugs:spotbugs-maven-plugin:check -DconfigFile=../config/checkStyle.xml"
            exit 1
          )
